# Site settings
title: Le joliblog de jolisylvain
email: jolisylvain@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  le joliblog de jolisylvain avec du jolicode et unjolietat d'esprit.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jolisylvain.github.io" # the base hostname & protocol for your site
twitter_username: jolisylvain
github_username:  jolisylvain

# Build settings
markdown: kramdown
